version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-api
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
    networks:
      - docker-service
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: docker-mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=food
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local
